import { sql, type SQL } from 'drizzle-orm'

/**
 * KIA Customer Profile — identity resolution.
 *
 * This is the ONLY place that decides who a customer is. Everything else consumes the
 * fragments exported here, so the rules cannot drift between the list, the profile and
 * the gap counts.
 *
 * THE MODEL — two keys and one bridge:
 *
 *   Key A  `customer_id`  ("C2025010002") is a real DMS party key and links the SALES side
 *          at 99.9-100%: booking->enquiry 1,203/1,204, receipt->enquiry 492/492,
 *          sales->enquiry 837/838, enquiry.booking_no->booking 1,146/1,146.
 *          No fuzzy matching is needed for sales.
 *
 *   Key B  `VIN` (upper-trimmed, 17 chars) keys the VEHICLE side — insurance, RO billing,
 *          PSF, appointments, complaints. VIN hygiene is perfect: zero rows anywhere where
 *          `vin <> upper(btrim(vin))`, every value 17 characters. A plain equi-join is safe.
 *
 *   Bridge `kia_sales_report` is the ONLY table holding both `customerid` and `vin_number`.
 *          Everything sales<->service flows through it. From 879 sales VINs it reaches
 *          ro_billing_report 95.4%, kia_insurance 91.4%, kia_psf_yearly 76.1%.
 *
 * ⚠️ The party-key column is `customer_id` in enquiry / booking / receipt / open_ro, but
 *    `customerid` (no underscore) in `kia_sales_report`. Getting this wrong yields silent
 *    zero-row joins, not an error.
 */

/* ------------------------------------------------------------------------------------ *
 * Normalisation
 * ------------------------------------------------------------------------------------ */

/**
 * Last 10 digits. Mirrors `phone10` in lib/callyzer/customer-match.ts:37-40 EXACTLY.
 *
 * ⚠️ Any index supporting a join on this expression must be written character-for-character
 * the same or Postgres will not use it — see lib/db/migrations/0026_add_phone10_match_indexes.sql,
 * whose comment records the cost of getting it wrong: 5,274 ms for a single 120-number page.
 *
 * KIA phones are in fact stored bare 10-digit with no +91, spaces or dashes anywhere, so this
 * is cheap insurance rather than a necessity — but the sources are external feeds and that
 * could change without warning.
 */
export function phone10Sql(column: SQL | ReturnType<typeof sql.raw>) {
  return sql`RIGHT(regexp_replace(COALESCE(${column}, ''), '\\D', '', 'g'), 10)`
}

/** TS twin of `phone10Sql`, for normalising user input before it reaches a query. */
export function phone10(value: string | null | undefined): string {
  const digits = String(value ?? '').replace(/\D/g, '')
  return digits.length >= 10 ? digits.slice(-10) : ''
}

/** VIN/chassis normalisation. Matches lib/insurance/cohorts.ts:70 (`UPPER(TRIM(...))`). */
export function vinSql(column: SQL | ReturnType<typeof sql.raw>) {
  return sql`UPPER(BTRIM(COALESCE(${column}, '')))`
}

/**
 * A valid 17-character VIN. Borrowed from app/api/insurance/policies/route.ts:74 — note the
 * excluded letters I, O and Q, which the VIN standard forbids because they read as 1 and 0.
 */
export const KIA_VIN_PATTERN = /^[A-HJ-NPR-Z0-9]{17}$/

export function normalizeVin(value: string | null | undefined): string {
  return String(value ?? '').trim().toUpperCase()
}

export function isVinLike(value: string | null | undefined): boolean {
  return KIA_VIN_PATTERN.test(normalizeVin(value))
}

/**
 * Registration numbers are NOT reliable across KIA sources and must never be a join key.
 * `kia_insurance.veh_regist_no` is populated on 21 of 1,401 rows (1.5%) and is dash-formatted
 * ("JK-02-CN-9806") while `ro_billing_report.vehicle_reg_no` is bare ("JK02CN9806"); stripping
 * separators recovers only 15 matches. This exists for SEARCH ONLY.
 */
export function registrationSql(column: SQL | ReturnType<typeof sql.raw>) {
  return sql`UPPER(regexp_replace(COALESCE(${column}, ''), '[^A-Za-z0-9]', '', 'g'))`
}

export function normalizeRegistration(value: string | null | undefined): string {
  return String(value ?? '').replace(/[^A-Za-z0-9]/g, '').toUpperCase()
}

/* ------------------------------------------------------------------------------------ *
 * Snapshot de-duplication
 * ------------------------------------------------------------------------------------ */

/**
 * ⚠️ THE SINGLE BIGGEST CORRECTNESS RISK IN THIS SECTION.
 *
 * `kia_enquiry_report` and `kia_booking_report` are CUMULATIVE RE-UPLOADED SNAPSHOTS, not
 * event logs. The same logical row is re-inserted on every feed run:
 *
 *     enquiry  88,319 rows for  8,110 customers  — one customer_id appears up to 183 times
 *     booking   2,101 rows for  1,147 bookings
 *
 * Querying them raw inflates every figure by roughly 10x and 2x respectively. Every read of
 * these tables MUST go through the CTEs below.
 *
 * ⚠️ Do NOT reach for `row_hash` to dedupe. Across this codebase that column is generated by
 * our own ingest, so every row carries a distinct value and `DISTINCT ON (row_hash)` is a
 * no-op that reads as protection. The same mistake overstated Hyundai VAS by 2.4x.
 */

/**
 * The de-duplication rules, in one place. Consumers build their own SELECT list around these
 * (the directory needs 12 columns, the profile needs different ones, and a SELECT * dedupe over
 * 88,319 enquiry rows costs seconds), but the KEYS and ORDER BY below are what make the result
 * correct and must not be varied.
 *
 *   enquiry    DISTINCT ON (customer_id, enquiry_no)  ORDER BY ..., uploaded_at DESC
 *   booking    DISTINCT ON (booking_no)               ORDER BY ..., uploaded_at DESC
 *   sales      DISTINCT ON (UPPER(BTRIM(vin_number))) ORDER BY ..., uploaded_at DESC
 *   insurance  DISTINCT ON (UPPER(BTRIM(vinno)))      ORDER BY ..., policy_expiry_date DESC
 *
 * `npm run verify:kia-customer-profile` asserts the deduped totals against the raw feeds, so
 * a consumer that drifts from these keys fails the build rather than quietly inflating.
 */
export const KIA_SNAPSHOT_DEDUPE_KEYS = {
  enquiry: ['customer_id', 'enquiry_no'],
  booking: ['booking_no'],
  sales: ['UPPER(BTRIM(vin_number))'],
  insurance: ['UPPER(BTRIM(vinno))'],
} as const

/* ------------------------------------------------------------------------------------ *
 * Profile keys
 * ------------------------------------------------------------------------------------ */

/**
 * A profile is keyed on the DMS party key when one exists, and on VIN otherwise.
 *
 * The VIN fallback is not an edge case: customers who have only ever used the workshop have
 * no `customer_id` at all — they exist in `ro_billing_report` / `kia_psf_yearly` keyed by
 * vehicle alone. Dropping them would silently remove a large, and very actionable, outreach
 * population from the section.
 */
export type KiaCustomerKey =
  | { kind: 'customer'; value: string }
  | { kind: 'vehicle'; value: string }

const CUSTOMER_ID_PATTERN = /^C\d{6,}$/i

export function parseCustomerKey(raw: string | null | undefined): KiaCustomerKey | null {
  const value = String(raw ?? '').trim()
  if (!value) return null

  if (value.startsWith('vin:')) {
    const vin = normalizeVin(value.slice(4))
    return isVinLike(vin) ? { kind: 'vehicle', value: vin } : null
  }
  if (value.startsWith('cid:')) {
    const id = value.slice(4).trim().toUpperCase()
    return id ? { kind: 'customer', value: id } : null
  }

  // Bare values: a 17-char VIN is unambiguous, and C-prefixed ids are the DMS format.
  const upper = value.toUpperCase()
  if (isVinLike(upper)) return { kind: 'vehicle', value: upper }
  if (CUSTOMER_ID_PATTERN.test(upper)) return { kind: 'customer', value: upper }
  return null
}

export function serializeCustomerKey(key: KiaCustomerKey): string {
  return key.kind === 'customer' ? `cid:${key.value}` : `vin:${key.value}`
}

/* ------------------------------------------------------------------------------------ *
 * Search-term classification
 * ------------------------------------------------------------------------------------ */

export type KiaSearchTerm = {
  raw: string
  phone: string
  vin: string
  registration: string
  name: string
  /** True when the term is specific enough that a name scan would only add noise. */
  isExact: boolean
}

/**
 * Classifies what the user typed so the search can use the cheapest precise index available
 * rather than scanning names for everything.
 *
 * ⚠️ Name is a SEARCH input, never an identity. app/api/insurance/vehicles/route.ts:32-56
 * documents this exact mistake being corrected once already: 12,563 chassis against 8,443
 * names, so grouping by name merged distinct vehicles under one person AND split one vehicle
 * across spelling variants. Names here only narrow a candidate list.
 */
export function classifySearchTerm(raw: string | null | undefined): KiaSearchTerm | null {
  const value = String(raw ?? '').trim()
  if (!value) return null

  const phone = phone10(value)
  const vin = isVinLike(value) ? normalizeVin(value) : ''
  const digitsOnly = /^\d+$/.test(value.replace(/\D/g, '')) && value.replace(/\D/g, '').length >= 10

  // Registration only when it looks like one: alphanumeric, has both letters and digits, and
  // is not already a VIN. Prevents every name fragment being treated as a plate.
  const compact = normalizeRegistration(value)
  const registration = !vin && compact.length >= 6 && compact.length <= 12
    && /[A-Z]/.test(compact) && /\d/.test(compact)
    ? compact
    : ''

  return {
    raw: value,
    phone: digitsOnly ? phone : '',
    vin,
    registration,
    name: value,
    isExact: Boolean(vin) || Boolean(digitsOnly && phone),
  }
}
