import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { SidebarProvider } from "@/context/sidebar-context";
import { DashboardQueryProvider } from "@/components/providers/query-provider";
import Script from "next/script";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

import NextTopLoader from 'nextjs-toploader';

const themeInitScript = `
  try {
    const storedTheme = window.localStorage.getItem('dashboard-theme');
    const prefersDark = window.matchMedia('(prefers-color-scheme: dark)').matches;
    if ((storedTheme && storedTheme === 'dark') || (!storedTheme && prefersDark)) {
      document.documentElement.classList.add('dark');
    }
  } catch (_) {}
`;

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${inter.variable} h-full antialiased`}
      suppressHydrationWarning
    >
      <body className="min-h-full flex flex-col">
        <Script
          id="dashboard-theme-init"
          strategy="beforeInteractive"
          dangerouslySetInnerHTML={{ __html: themeInitScript }}
        />
        <NextTopLoader 
          color="#ffffff"
          initialPosition={0.08}
          crawlSpeed={200}
          height={3}
          crawl={true}
          showSpinner={false}
          easing="ease"
          speed={200}
          shadow="0 0 12px rgba(255,255,255,0.85),0 0 6px rgba(255,255,255,0.6)"
        />
        <DashboardQueryProvider>
          <SidebarProvider>
            {children}
          </SidebarProvider>
        </DashboardQueryProvider>
      </body>
    </html>
  );
}
