import { sql } from 'drizzle-orm'
import { analyticsDb as db } from '@/lib/analytics/db'
import { hyundaiSourceDealerFilter } from '@/lib/hyundai/dealer-branch'
import {
  HYUNDAI_VAS_IDENTIFIER_VERSION,
  hyundaiVasCodeSql,
  hyundaiWheelAlignmentCodeSql,
  hyundaiWheelBalancingCodeSql,
} from '@/lib/hyundai/vas-identifiers'

type Row = Record<string, unknown>

export type HyundaiMonthlyOperationMetrics = {
  available: boolean
  periodStart: string | null
  periodEnd: string | null
  vasAmount: number
  vasRows: number
  waCount: number
  waAmount: number
  wbCount: number
  wbAmount: number
  sourceRows: number
  classifiedRows: number
  unknownCodeRows: number
  unknownCodes: string[]
  identifierVersion: string
}

function rows(value: unknown): Row[] {
  return Array.isArray(value) ? value as Row[] : []
}

function numberValue(value: unknown) {
  const parsed = Number(value || 0)
  return Number.isFinite(parsed) ? parsed : 0
}

function dateValue(value: unknown) {
  return value ? String(value).slice(0, 10) : null
}

function dealerFilter(dealerCode: string | null, alias = '') {
  return hyundaiSourceDealerFilter(
    dealerCode,
    sql.raw(`${alias}source_dealer_code`),
    [sql.raw(`${alias}dealer_code`)],
  )
}

function getMonthRange(dateInput: string) {
  const anchor = new Date(`${dateInput}T00:00:00Z`)
  const monthStart = new Date(Date.UTC(anchor.getUTCFullYear(), anchor.getUTCMonth(), 1))
  const nextMonthStart = new Date(Date.UTC(anchor.getUTCFullYear(), anchor.getUTCMonth() + 1, 1))

  return {
    monthStart: monthStart.toISOString().slice(0, 10),
    nextMonthStart: nextMonthStart.toISOString().slice(0, 10),
  }
}

export async function fetchHyundaiMonthlyOperationMetrics(
  endDate: string,
  dealerCode: string | null = null,
): Promise<HyundaiMonthlyOperationMetrics> {
  const empty = (): HyundaiMonthlyOperationMetrics => ({
    available: false,
    periodStart: null,
    periodEnd: null,
    vasAmount: 0,
    vasRows: 0,
    waCount: 0,
    waAmount: 0,
    wbCount: 0,
    wbAmount: 0,
    sourceRows: 0,
    classifiedRows: 0,
    unknownCodeRows: 0,
    unknownCodes: [],
    identifierVersion: HYUNDAI_VAS_IDENTIFIER_VERSION,
  })

  if (!(await db.tableExists('hyundai_operation_wise_analysis_report'))) return empty()

  const { monthStart, nextMonthStart } = getMonthRange(endDate)

  let result: unknown
  try {
    result = await db.execute(sql`
    WITH candidate_period AS (
      SELECT report_period_start::date AS period_start, report_period_end::date AS period_end
      FROM hyundai_operation_wise_analysis_report
      WHERE report_period_start >= ${monthStart}::date
        AND report_period_start < ${nextMonthStart}::date
        AND report_type = 'Operation'
        ${dealerFilter(dealerCode)}
      GROUP BY report_period_start::date, report_period_end::date
      ORDER BY
        (COUNT(*) > 100) DESC,
        report_period_end::date DESC,
        report_period_start::date DESC
      LIMIT 1
    ),
    -- One upload batch per dealer. The same (dealer, period, report_type) is uploaded more
    -- than once -- a partial early run and then the complete file -- and both sets of rows
    -- are retained. Deduping on row_hash cannot help: row_hash is generated by our own cron
    -- on insert, so every row carries a distinct value and DISTINCT ON row_hash is a no-op.
    -- Summing every upload inflated July VAS from Rs16,99,979 to Rs40,17,728.
    latest_upload AS (
      SELECT
        ${sql.raw("UPPER(TRIM(COALESCE(src.source_dealer_code, src.dealer_code, '')))")} AS dealer,
        MAX(src.uploaded_at) AS uploaded_at
      FROM hyundai_operation_wise_analysis_report src
      JOIN candidate_period period
        ON src.report_period_start::date = period.period_start
       AND src.report_period_end::date = period.period_end
      WHERE src.report_type = 'Operation'
        ${dealerFilter(dealerCode, 'src.')}
      GROUP BY 1
    ),
    latest AS (
      SELECT
        UPPER(TRIM(COALESCE(source.op_part_code, ''))) AS code,
        COALESCE(source.total_amt, 0)::numeric AS amount,
        COALESCE(source.total_count, 0)::numeric AS quantity
      FROM hyundai_operation_wise_analysis_report source
      JOIN candidate_period period
        ON source.report_period_start::date = period.period_start
       AND source.report_period_end::date = period.period_end
      JOIN latest_upload picked
        ON picked.dealer = ${sql.raw("UPPER(TRIM(COALESCE(source.source_dealer_code, source.dealer_code, '')))")}
       AND picked.uploaded_at = source.uploaded_at
      -- VAS, wheel alignment and wheel balancing are all operation codes; 'Part' rows carry
      -- none of them and only pollute the unknown-code diagnostics.
      WHERE source.report_type = 'Operation'
        ${dealerFilter(dealerCode, 'source.')}
    )
    SELECT
      MIN(period.period_start)::text AS period_start,
      MAX(period.period_end)::text AS period_end,
      COUNT(latest.code)::int AS source_rows,
      COUNT(*) FILTER (WHERE ${hyundaiVasCodeSql(sql.raw('latest.code'))})::int AS vas_rows,
      COALESCE(SUM(amount) FILTER (WHERE ${hyundaiVasCodeSql(sql.raw('latest.code'))}), 0)::float AS vas_amount,
      COALESCE(SUM(quantity) FILTER (WHERE ${hyundaiWheelAlignmentCodeSql(sql.raw('latest.code'))}), 0)::float AS wa_count,
      COALESCE(SUM(amount) FILTER (WHERE ${hyundaiWheelAlignmentCodeSql(sql.raw('latest.code'))}), 0)::float AS wa_amount,
      COALESCE(SUM(quantity) FILTER (WHERE ${hyundaiWheelBalancingCodeSql(sql.raw('latest.code'))}), 0)::float AS wb_count,
      COALESCE(SUM(amount) FILTER (WHERE ${hyundaiWheelBalancingCodeSql(sql.raw('latest.code'))}), 0)::float AS wb_amount,
      COUNT(*) FILTER (
        WHERE ${hyundaiVasCodeSql(sql.raw('latest.code'))}
          OR ${hyundaiWheelAlignmentCodeSql(sql.raw('latest.code'))}
          OR ${hyundaiWheelBalancingCodeSql(sql.raw('latest.code'))}
      )::int AS classified_rows,
      COUNT(*) FILTER (
        WHERE latest.code <> ''
          AND NOT (${hyundaiVasCodeSql(sql.raw('latest.code'))})
          AND NOT (${hyundaiWheelAlignmentCodeSql(sql.raw('latest.code'))})
          AND NOT (${hyundaiWheelBalancingCodeSql(sql.raw('latest.code'))})
      )::int AS unknown_code_rows,
      ARRAY(
        SELECT DISTINCT unknown.code
        FROM latest unknown
        WHERE unknown.code <> ''
          AND NOT (${hyundaiVasCodeSql(sql.raw('unknown.code'))})
          AND NOT (${hyundaiWheelAlignmentCodeSql(sql.raw('unknown.code'))})
          AND NOT (${hyundaiWheelBalancingCodeSql(sql.raw('unknown.code'))})
        ORDER BY unknown.code
        LIMIT 25
      ) AS unknown_codes
    FROM candidate_period period
    LEFT JOIN latest ON TRUE
    `)
  } catch (error) {
    const code = String((error as { cause?: { code?: unknown }; code?: unknown })?.cause?.code
      || (error as { code?: unknown })?.code
      || '')
    if (code === '42703' || code === '42P01') return empty()
    throw error
  }

  const row = rows(result)[0] || {}
  const periodStart = dateValue(row.period_start)
  return {
    available: Boolean(periodStart),
    periodStart,
    periodEnd: dateValue(row.period_end),
    vasAmount: numberValue(row.vas_amount),
    vasRows: numberValue(row.vas_rows),
    waCount: numberValue(row.wa_count),
    waAmount: numberValue(row.wa_amount),
    wbCount: numberValue(row.wb_count),
    wbAmount: numberValue(row.wb_amount),
    sourceRows: numberValue(row.source_rows),
    classifiedRows: numberValue(row.classified_rows),
    unknownCodeRows: numberValue(row.unknown_code_rows),
    unknownCodes: Array.isArray(row.unknown_codes)
      ? row.unknown_codes.map(String)
      : [],
    identifierVersion: HYUNDAI_VAS_IDENTIFIER_VERSION,
  }
}
