import { sql } from 'drizzle-orm'

export const PLATINUM_VAS_IDENTIFIER_VERSION = 'vas-report-2026-06-19-v3'

export const PLATINUM_VAS_CODES = [
  'A10AA1LCERAHR',
  'A10AAACDVASHR',
  'A10AAACDVASHRAA',
  'A10AAACDVASHRHW',
  'A10AAACDVASWT',
  'A10AAATLVASHR',
  'A10AAATLVASHRHW',
  'A10AAATMVASHR',
  'A10AAATMVASHRHW',
  'A10AAATSVASHR',
  'A10AAATSVASHRHW',
  'A10AAAWPVASHR',
  'A10AAAWPVASHRAA',
  'A10AAAWPVASWT',
  'A10AAEBLVAS3M',
  'A10AAEBLVASHR',
  'A10AAEBMVASHR',
  'A10AAEBSVASHR',
  'A10AAECLVAS3M',
  'A10AAECLVASEB',
  'A10AAECLVASHR',
  'A10AAECLVASHRAA',
  'A10AAECLVASWT',
  'A10AAECMVAS3M',
  'A10AAECMVASEB',
  'A10AAECMVASHR',
  'A10AAECMVASHRHW',
  'A10AAECMVASWT',
  'A10AAECMVASWTHW',
  'A10AAECSVASEBHW',
  'A10AAECSVASHR',
  'A10AAECSVASHRHW',
  'A10AAECSVASWT',
  'A10AAECSVASWTHW',
  'A10AAEGRVASHR',
  'A10AAEGRVASHRAA',
  'A10AAGM05TBCL',
  'A10AAHLRVASHR',
  'A10AAIALVASWT',
  'A10AAIAMVASWT',
  'A10AAIAMVASWTHW',
  'A10AAIASVASWT',
  'A10AAIELVASHR',
  'A10AAIEMVASHR',
  'A10AAIESVASHR',
  'A10AAISSVALHR',
  'A10AAISSVAMHR',
  'A10AAISSVASHR',
  'A10AALUB03LNA',
  'A10AAPILVAS3M',
  'A10AAPILVASEB',
  'A10AAPILVASHR',
  'A10AAPIMVASHR',
  'A10AAPISVASHR',
  'A10AAPPLVASHR',
  'A10AAPPLVASWT',
  'A10AAPPLVASWTAA',
  'A10AAPPMVASHR',
  'A10AAPPMVASHRHW',
  'A10AAPPMVASWT',
  'A10AAPPSVASHR',
  'A10AAPPSVASWT',
  'A10AARRLVASHR',
  'A10AARRMVASHR',
  'A10AARRSVASHR',
  'A10AARUB19LNA',
  'A10AASA68CROS',
  'A10AASA68CROSAA',
  'A10AASCLVASHR',
  'A10AASCLVASHRAA',
  'A10AASCMVAS3M',
  'A10AASCMVASEB',
  'A10AASCMVASHR',
  'A10AASCMVASWT',
  'A10AASCSVAS3M',
  'A10AASCSVASEB',
  'A10AASCSVASHR',
  'A10AASCSVASWT',
  'A10AASPLVAS3M',
  'A10AASPLVASEB',
  'A10AASPLVASHR',
  'A10AASPLVASHRAA',
  'A10AASPLVASHRHW',
  'A10AASPLVASWT',
  'A10AASPMVAS3M',
  'A10AASPMVASHR',
  'A10AASPMVASHRAA',
  'A10AASPMVASHRHW',
  'A10AASPMVASWT',
  'A10AASPSVASEB',
  'A10AASPSVASHR',
  'A10AASPSVASHRHW',
  'A10AASPSVASWT',
  'A10AATBC0003M',
  'A10AATBC000HR',
  'A10AATBC000HRHW',
  'A10AATBC000WR',
  'A10AATBC000WT',
  'A10AATBC000WTHW',
  'A10AAUBCAL03M',
  'A10AAUBCAL0HR',
  'A10AAUBCAL0HRAA',
  'A10AAUBCAL0WR',
  'A10AAUBCAS03M',
  'A10AAUBCAS0EB',
  'A10AAUBCAS0HR',
  'A10AAUBCAS0WR',
  'A10AAUBCAS0WT',
  'A10AAWTSVASHR',
  'A10AAACDVAS3M',
  'A10AAACDVASEB',
  'A10AAACDVASEBHW',
  'A10AAACDVASWTAA',
  'A10AAACDVASWTHW',
  'A10AAATLVASHRAA',
  'A10AAAWPVASHRHW',
  'A10AAEBLVASEB',
  'A10AAEBLVASWT',
  'A10AAEBMVAS3M',
  'A10AAEBMVASEB',
  'A10AAEBMVASHRHW',
  'A10AAEBMVASWT',
  'A10AAEBMVASWTHW',
  'A10AAEBSVAS3M',
  'A10AAEBSVASEB',
  'A10AAEBSVASWT',
  'A10AAECLVASWTAA',
  'A10AAECMVAS3MHW',
  'A10AAECMVASEBHW',
  'A10AAECSVAS3M',
  'A10AAECSVAS3MHW',
  'A10AAECSVASEB',
  'A10AAEGRVASEB',
  'A10AAEMCVASHR',
  'A10AAEVCVASEB',
  'A10AAEVCVASHR',
  'A10AAHLRVAS3M',
  'A10AAHLRVASEB',
  'A10AAIALVAS3M',
  'A10AAIALVASEB',
  'A10AAIALVASWR',
  'A10AAIALVASWTAA',
  'A10AAIAMNVAS3M',
  'A10AAIAMVAS3M',
  'A10AAIAMVASEB',
  'A10AAIAMVASWTAA',
  'A10AAIASNVAS3M',
  'A10AAIASVAS3M',
  'A10AAIASVASEB',
  'A10AAIASVASWR',
  'A10AAIASVASWTHW',
  'A10AAIELVAS3M',
  'A10AAIELVASEB',
  'A10AAIELVASHRAA',
  'A10AAIEMVAS3M',
  'A10AAIEMVASEB',
  'A10AAIEMVASHRHW',
  'A10AAIEMVASWT',
  'A10AAIESVASEB',
  'A10AAIESVASWT',
  'A10AAISSVALHRAA',
  'A10AAISSVAMHRAA',
  'A10AAISSVAMHRHW',
  'A10AAISSVAMWT',
  'A10AAISSVASAR',
  'A10AAISSVASEB',
  'A10AAISSVASHRAA',
  'A10AAISSVASWR',
  'A10AAISSVASWT',
  'A10AAPILVASWT',
  'A10AAPILVASWTAA',
  'A10AAPIMVAS3M',
  'A10AAPIMVASEB',
  'A10AAPIMVASHRHW',
  'A10AAPIMVASWT',
  'A10AAPISVASEB',
  'A10AAPISVASHRHW',
  'A10AAPISVASWTHW',
  'A10AAPMSVAS01',
  'A10AAPMSVAS02',
  'A10AAPPLVAS3M',
  'A10AAPPLVASHRAA',
  'A10AAPPMVAS3M',
  'A10AAPPSVAS3M',
  'A10AAPPSVASEB',
  'A10AAPPSVASHRHW',
  'A10AARRLVASEB',
  'A10AARRMVASEB',
  'A10AARRSVASEB',
  'A10AARRSVASHRHW',
  'A10AASA68CROSHW',
  'A10AASCLVAS3M',
  'A10AASCLVASEB',
  'A10AASCLVASWT',
  'A10AASCSVASHRHW',
  'A10AASPMVASEB',
  'A10AASPSVAS3M',
  'A10AATBC000EB',
  'A10AATBC000HRAA',
  'A10AATBC000WM',
  'A10AATBC000WRHW',
  'A10AATBC000WTAA',
  'A10AAUBCAL0EB',
  'A10AAUBCAL0WT',
  'A10AAUBCAL0WTAA',
  'A10AAUBCAS0HRHW',
  'A10AAUBCAS0WTHW',
] as const

export const PLATINUM_WHEEL_ALIGNMENT_CODES = [
  'A10AAGM06WHAL',
  'A10AAGM06WHALAA',
  'A10AAGM06WHALHW',
] as const

export const PLATINUM_WHEEL_BALANCING_CODES = [
  'A10AAGM07WHBL',
  'A10AAGM07WHBLAA',
  'A10AAGM07WHBLHW',
] as const

export const PLATINUM_FUEL_INJECTOR_CODES = ['A10AAGM04FICL'] as const

export const PLATINUM_ADVISOR_DEPARTMENTS = {
  'ABHISHEK SALGOTRA': 'MECH',
  'AJAY KUMAR': 'B/S',
  'AJAY SINGH': 'MECH',
  'AMAN KUMAR': 'MECH',
  'AMANDEEP SINGH GAIDU': 'MECH',
  'AMIT DOGRA': 'B/S',
  'AMIT SHARMA': 'MECH',
  'ANIL KUMAR': 'MECH',
  'ANKUSH LOUCH': 'MECH',
  'ATISH KUMAR': 'MECH',
  'AVLEEN SINGH SONI': 'MECH',
  'BILAL MIRZA': 'B/S',
  'DEEPAK KUMAR': 'MECH',
  'DEEPAK KUMAR SUPWAL': 'B/S',
  'GHARA RAM': 'MECH',
  'HARI DEEP SHARMA': 'MECH',
  'HARSHVEER SINGH': 'MECH',
  'JYOTI BALA': 'MECH',
  'KARAN BHARDWAJ': 'B/S',
  'KULBUSHAN KUMAR': 'B/S',
  'MOHD ANIES': 'MECH',
  'MUSHTAQ AHMED': 'MECH',
  'NARESH KUMAR': 'MECH',
  'NARESH KUMAR SUPWAL': 'B/S',
  'PARVEEN KUMAR': 'MECH',
  'PRANAV ARORA': 'B/S',
  'PUPINDER SINGH': 'MECH',
  'RAGHU KALOTRA': 'MECH',
  'RAHUL SALGOTRA': 'B/S',
  'RAMESHWAR DAMRAL': 'MECH',
  'RISHAB': 'MECH',
  'ROBIN RAINA': 'B/S',
  'ROHIT KUMAR': 'B/S',
  'SAHAJ SANT': 'B/S',
  'SAHIL CHOUHAN': 'MECH',
  'SAHIL JAMWAL': 'MECH',
  'SAMRAT GUPTA': 'MECH',
  'SANJAY KUMAR': 'MECH',
  'SANJEEV KUMAR': 'MECH',
  'SATISH KUMAR': 'B/S',
  'SHUBHAM MONA': 'MECH',
  'SHUBHAM SINGH BHAU': 'MECH',
  'SOURAV KUMAR': 'B/S',
  'SUMIT KUMAR': 'MECH',
  'TANIYA DOGRA': 'MECH',
  'VARIS SINGH CHIB': 'MECH',
  'VIKAS SHARMA': 'B/S',
  'VISHAL KUMAR': 'MECH',
  'VISHAL KUMAR 2': 'MECH',
  'VISHAVJEET SINGH': 'MECH',
} as const

export const PLATINUM_ALL_IDENTIFIER_CODES = [
  ...PLATINUM_VAS_CODES,
  ...PLATINUM_WHEEL_ALIGNMENT_CODES,
  ...PLATINUM_WHEEL_BALANCING_CODES,
  ...PLATINUM_FUEL_INJECTOR_CODES,
] as const

export type PlatinumOperationCategory = 'vas' | 'wheel_alignment' | 'wheel_balancing' | 'fuel_injector' | 'unknown'

const VAS_CODE_SET = new Set<string>(PLATINUM_VAS_CODES)
const WHEEL_ALIGNMENT_CODE_SET = new Set<string>(PLATINUM_WHEEL_ALIGNMENT_CODES)
const WHEEL_BALANCING_CODE_SET = new Set<string>(PLATINUM_WHEEL_BALANCING_CODES)
const FUEL_INJECTOR_CODE_SET = new Set<string>(PLATINUM_FUEL_INJECTOR_CODES)

export function normalizePlatinumOperationCode(value: unknown) {
  return String(value || '').trim().toUpperCase()
}

export function classifyPlatinumOperationCode(value: unknown): PlatinumOperationCategory {
  const code = normalizePlatinumOperationCode(value)
  if (VAS_CODE_SET.has(code)) return 'vas'
  if (WHEEL_ALIGNMENT_CODE_SET.has(code)) return 'wheel_alignment'
  if (WHEEL_BALANCING_CODE_SET.has(code)) return 'wheel_balancing'
  if (FUEL_INJECTOR_CODE_SET.has(code)) return 'fuel_injector'
  return 'unknown'
}

export function platinumCodeInSql(column: ReturnType<typeof sql.raw>, codes: readonly string[]) {
  return sql`UPPER(TRIM(COALESCE(${column}::text, ''))) IN (${sql.join(codes.map((code) => sql`${code}`), sql`, `)})`
}

export function platinumVasCodeSql(column: ReturnType<typeof sql.raw>) {
  return platinumCodeInSql(column, PLATINUM_VAS_CODES)
}

export function platinumKnownCodeSql(column: ReturnType<typeof sql.raw>) {
  return platinumCodeInSql(column, PLATINUM_ALL_IDENTIFIER_CODES)
}

export function platinumWheelAlignmentCodeSql(column: ReturnType<typeof sql.raw>) {
  return platinumCodeInSql(column, PLATINUM_WHEEL_ALIGNMENT_CODES)
}

export function platinumWheelBalancingCodeSql(column: ReturnType<typeof sql.raw>) {
  return platinumCodeInSql(column, PLATINUM_WHEEL_BALANCING_CODES)
}

export function platinumAdvisorDepartmentSql(column: ReturnType<typeof sql.raw>) {
  const cases = Object.entries(PLATINUM_ADVISOR_DEPARTMENTS).map(
    ([advisor, department]) => sql`WHEN UPPER(TRIM(COALESCE(${column}::text, ''))) = ${advisor} THEN ${department}`
  )
  return sql`CASE ${sql.join(cases, sql` `)} ELSE 'UNMAPPED' END`
}
