-- 0059 Rollback
BEGIN;
ALTER TABLE IF EXISTS public.am_hyundai_trips NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.items_row NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.mg_trips NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.platinum_test_drive_vehicle NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.trips NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kia_vehicle NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."TATA_employees" NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kia_employees NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.tata_trips NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public.kia_trips NO FORCE ROW LEVEL SECURITY;
ALTER TABLE IF EXISTS public."TATA_vehicle" NO FORCE ROW LEVEL SECURITY;
COMMIT;
NOTIFY pgrst, 'reload schema';
