-- 0072 — AM Tata "H Promise": the pre-owned car desk (purchase → booking → sale → paperwork → approvals → ledger).
--
-- ⚠️ APPLY BY HAND ON THE DIRECT/SESSION PORT 5432 (scripts/apply-migration-0072.ts). DDL must not run on the
--    pgbouncer pooler (6543).
--
-- ── Why this exists (owner decisions, 2026-09-17) ───────────────────────────────────────────────
-- AM Tata ran its used-car business in a Google Apps Script web app over one Google Sheet. H Promise replaces it.
-- The sheet kept everything in one 69-column row and reused columns for two things (the booking date was written
-- into a column the sale form also wrote, and the MIS read the booking RECEIPT column as a date). Here:
--
--   tata_h_promise_vehicles         one row per vehicle lifecycle: purchase, sale, paperwork, both approvals
--   tata_h_promise_bookings         bookings in their own table, so book → refund → rebook is possible
--   tata_h_promise_files            every uploaded file; replacing one keeps the old row (superseded_at)
--   tata_h_promise_events           append-only history: who changed what, when
--   tata_h_promise_options          the editable name lists (staff, WhatsApp approvers, locations)
--   tata_h_promise_settings         effective-dated rates for the profit/interest formulas
--   tata_h_promise_exchange_bonuses the small exchange-bonus register the sheet kept on its own tab
--
-- House rules followed: status columns are free TEXT (0050) — a new value never needs a migration and never
-- becomes an enum outage. Money is numeric(14,2). The lifecycle stage (in stock / booked / sold) is DERIVED in
-- lib/h-promise/stage.ts, never stored, so it cannot disagree with the facts it is derived from. Price with GST
-- is computed, not stored, for the same reason.
--
-- Safeguards the owner chose, enforced HERE as well as in the app, so a future code path cannot skip them:
--   · nobody decides their own entry (CHECK constraints below);
--   · an approved purchase or sale price cannot change until an approver reopens it (trigger below);
--   · full change history (tata_h_promise_events is append-only).

BEGIN;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- 1. Vehicles
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tata_h_promise_vehicles (
  id                            uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Shown as HP-00042. An identity, not a row count: the sheet derived its ID from the row count, which two
  -- people saving at once turned into the same ID.
  stock_no                      integer GENERATED BY DEFAULT AS IDENTITY UNIQUE NOT NULL,
  reg_no                        text NOT NULL,
  -- The comparison key: JK02AB1234, 'jk 02 ab-1234' and 'JK-02-AB-1234' are the same car.
  -- Mirrored exactly by normalizeRegNo() in lib/h-promise/registration.ts.
  reg_no_key                    text GENERATED ALWAYS AS (upper(regexp_replace(reg_no, '[^A-Za-z0-9]', '', 'g'))) STORED,

  model                         text NOT NULL,
  colour                        text,
  manufacturing_year            smallint,
  odometer_km                   integer,
  engine_no                     text,
  chassis_no                    text,
  location                      text NOT NULL,

  -- Purchase
  purchase_date                 date NOT NULL,
  purchase_price                numeric(14,2) NOT NULL,
  purchase_gst_pct              numeric(5,2) NOT NULL DEFAULT 0,
  expected_profit               numeric(14,2),
  purchase_remarks              text,
  purchase_financed             boolean NOT NULL DEFAULT false,
  purchased_by                  text NOT NULL,
  sales_consultant              text,
  -- Phone formats are validated by the app (10 digits). Not a CHECK: imported sheet values are kept as found
  -- and reported, rather than silently dropped.
  seller_phone                  text,
  -- Who gave the go-ahead on WhatsApp — an option value, or 'NOT_TAKEN'. A record of the phone call, NOT the
  -- in-app approval below.
  purchase_whatsapp_approver    text NOT NULL,
  purchase_status               text NOT NULL DEFAULT 'pending',       -- pending | approved | rejected
  purchase_submitted_by         uuid REFERENCES public.users (id),
  purchase_submitted_by_name    text,
  purchase_submitted_at         timestamptz,
  purchase_decided_by           uuid REFERENCES public.users (id),
  purchase_decided_by_name      text,
  purchase_decided_at           timestamptz,
  purchase_decision_reason      text,

  -- Sale (one per vehicle lifecycle; a buy-back is a new row)
  sale_status                   text,                                  -- NULL | pending | approved | rejected
  sale_date                     date,
  selling_price                 numeric(14,2),
  other_cost                    numeric(14,2) NOT NULL DEFAULT 0,
  is_demo                       boolean,
  sold_to                       text,                                  -- CUSTOMER | BROKER | SCRAP
  sale_financed                 boolean,
  sold_by                       text,
  buyer_name                    text,
  buyer_phone                   text,
  buyer_address                 text,
  sale_whatsapp_approver        text,
  sale_submitted_by             uuid REFERENCES public.users (id),
  sale_submitted_by_name        text,
  sale_submitted_at             timestamptz,
  sale_decided_by               uuid REFERENCES public.users (id),
  sale_decided_by_name          text,
  sale_decided_at               timestamptz,
  sale_decision_reason          text,

  -- Vehicle paperwork
  insurance_end_date            date,
  -- Both: NOT_REQUIRED | REQUIRED | UNDER_PROCESS | DOCUMENT_UPLOADED (the sheet's HYP and RTO status columns)
  hypothecation                 text,
  rto_status                    text,
  documents_remarks             text,
  documents_updated_by          uuid REFERENCES public.users (id),
  documents_updated_by_name     text,
  documents_updated_at          timestamptz,

  -- RC transfer, for vehicles sold to a broker
  broker_rc_remarks             text,
  broker_rc_updated_by          uuid REFERENCES public.users (id),
  broker_rc_updated_by_name     text,
  broker_rc_updated_at          timestamptz,

  -- Payment ledger check (the ledger FILE lives in tata_h_promise_files)
  payment_verified_by           uuid REFERENCES public.users (id),
  payment_verified_by_name      text,
  payment_verified_at           timestamptz,

  created_by                    uuid REFERENCES public.users (id),
  created_by_name               text NOT NULL,
  created_at                    timestamptz NOT NULL DEFAULT now(),
  updated_by                    uuid REFERENCES public.users (id),
  updated_by_name               text,
  updated_at                    timestamptz NOT NULL DEFAULT now(),
  deleted_at                    timestamptz,
  deleted_by                    uuid REFERENCES public.users (id),
  deleted_by_name               text,
  delete_reason                 text,
  import_batch                  text,
  import_row                    integer,

  CONSTRAINT tata_h_promise_vehicles_reg_key_len       CHECK (length(reg_no_key) >= 4),
  CONSTRAINT tata_h_promise_vehicles_year_range        CHECK (manufacturing_year IS NULL OR manufacturing_year BETWEEN 1980 AND 2100),
  CONSTRAINT tata_h_promise_vehicles_odometer_nonneg   CHECK (odometer_km IS NULL OR odometer_km >= 0),
  CONSTRAINT tata_h_promise_vehicles_price_positive    CHECK (purchase_price > 0),
  CONSTRAINT tata_h_promise_vehicles_gst_range         CHECK (purchase_gst_pct >= 0 AND purchase_gst_pct <= 100),
  CONSTRAINT tata_h_promise_vehicles_selling_nonneg    CHECK (selling_price IS NULL OR selling_price >= 0),
  CONSTRAINT tata_h_promise_vehicles_other_cost_nonneg CHECK (other_cost >= 0),
  CONSTRAINT tata_h_promise_vehicles_sale_complete     CHECK (
    sale_status IS NULL OR (sale_date IS NOT NULL AND selling_price IS NOT NULL AND sold_to IS NOT NULL)
  ),
  -- No self-approval (owner decision). NULL-safe, so imported rows with no recorded people still pass.
  CONSTRAINT tata_h_promise_vehicles_purchase_not_self_created CHECK (
    purchase_decided_by IS NULL OR created_by IS NULL OR purchase_decided_by <> created_by
  ),
  CONSTRAINT tata_h_promise_vehicles_purchase_not_self_submitted CHECK (
    purchase_decided_by IS NULL OR purchase_submitted_by IS NULL OR purchase_decided_by <> purchase_submitted_by
  ),
  CONSTRAINT tata_h_promise_vehicles_sale_not_self_submitted CHECK (
    sale_decided_by IS NULL OR sale_submitted_by IS NULL OR sale_decided_by <> sale_submitted_by
  )
);

-- One live record per registration. A car whose sale is APPROVED has left the business, so buying the same car
-- back later opens a fresh lifecycle instead of colliding with the old one.
CREATE UNIQUE INDEX IF NOT EXISTS tata_h_promise_vehicles_reg_live_key
  ON public.tata_h_promise_vehicles (reg_no_key)
  WHERE deleted_at IS NULL AND sale_status IS DISTINCT FROM 'approved';

CREATE INDEX IF NOT EXISTS tata_h_promise_vehicles_reg_idx
  ON public.tata_h_promise_vehicles (reg_no_key);
CREATE INDEX IF NOT EXISTS tata_h_promise_vehicles_chassis_idx
  ON public.tata_h_promise_vehicles (chassis_no) WHERE chassis_no IS NOT NULL;
CREATE INDEX IF NOT EXISTS tata_h_promise_vehicles_purchase_date_idx
  ON public.tata_h_promise_vehicles (purchase_date DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS tata_h_promise_vehicles_sale_date_idx
  ON public.tata_h_promise_vehicles (sale_date DESC) WHERE deleted_at IS NULL AND sale_status IS NOT NULL;
CREATE INDEX IF NOT EXISTS tata_h_promise_vehicles_purchase_pending_idx
  ON public.tata_h_promise_vehicles (created_at) WHERE deleted_at IS NULL AND purchase_status = 'pending';
CREATE INDEX IF NOT EXISTS tata_h_promise_vehicles_sale_pending_idx
  ON public.tata_h_promise_vehicles (sale_submitted_at) WHERE deleted_at IS NULL AND sale_status = 'pending';

-- Prices lock once approved (owner decision). Reopening is its own step: approved → pending first, then the edit,
-- then a fresh approval — so the change is visible in the history and needs an approver again.
CREATE OR REPLACE FUNCTION public.tata_h_promise_price_lock()
  RETURNS trigger
  LANGUAGE plpgsql
  SET search_path = ''
AS $$
BEGIN
  IF OLD.purchase_status = 'approved' AND NEW.purchase_status = 'approved'
     AND (NEW.purchase_price IS DISTINCT FROM OLD.purchase_price
          OR NEW.purchase_gst_pct IS DISTINCT FROM OLD.purchase_gst_pct) THEN
    RAISE EXCEPTION 'H Promise: the purchase price is locked after approval. Reopen the purchase first.'
      USING ERRCODE = 'HP001';
  END IF;
  IF OLD.sale_status = 'approved' AND NEW.sale_status = 'approved'
     AND NEW.selling_price IS DISTINCT FROM OLD.selling_price THEN
    RAISE EXCEPTION 'H Promise: the selling price is locked after approval. Reopen the sale first.'
      USING ERRCODE = 'HP001';
  END IF;
  RETURN NEW;
END;
$$;

CREATE OR REPLACE TRIGGER tata_h_promise_price_lock
  BEFORE UPDATE ON public.tata_h_promise_vehicles
  FOR EACH ROW EXECUTE FUNCTION public.tata_h_promise_price_lock();

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- 2. Bookings
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tata_h_promise_bookings (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id          uuid NOT NULL REFERENCES public.tata_h_promise_vehicles (id) ON DELETE RESTRICT,
  status              text NOT NULL DEFAULT 'active',                  -- active | refunded
  booking_date        date NOT NULL,
  amount              numeric(14,2) NOT NULL,
  remarks             text,
  refund_date         date,
  refund_remarks      text,
  refunded_by         uuid REFERENCES public.users (id),
  refunded_by_name    text,
  refunded_at         timestamptz,
  created_by          uuid REFERENCES public.users (id),
  created_by_name     text NOT NULL,
  created_at          timestamptz NOT NULL DEFAULT now(),
  updated_by          uuid REFERENCES public.users (id),
  updated_by_name     text,
  updated_at          timestamptz NOT NULL DEFAULT now(),
  import_batch        text,
  import_row          integer,
  CONSTRAINT tata_h_promise_bookings_amount_positive CHECK (amount > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tata_h_promise_bookings_one_active
  ON public.tata_h_promise_bookings (vehicle_id) WHERE status = 'active';
CREATE INDEX IF NOT EXISTS tata_h_promise_bookings_vehicle_idx
  ON public.tata_h_promise_bookings (vehicle_id, booking_date DESC);
CREATE INDEX IF NOT EXISTS tata_h_promise_bookings_date_idx
  ON public.tata_h_promise_bookings (booking_date DESC);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- 3. Files
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- A staged upload has attached_at NULL until the form that uses it is saved, in the same transaction. Replacing
-- a file marks the old row superseded — it is kept, so "who uploaded the PAN we approved against" stays answerable.
CREATE TABLE IF NOT EXISTS public.tata_h_promise_files (
  id                  uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  vehicle_id          uuid REFERENCES public.tata_h_promise_vehicles (id) ON DELETE RESTRICT,
  booking_id          uuid REFERENCES public.tata_h_promise_bookings (id) ON DELETE RESTRICT,
  kind                text NOT NULL,
  -- Object path in the PRIVATE tata-h-promise bucket. Never a public URL; read back through a short signed URL.
  storage_path        text NOT NULL UNIQUE,
  content_type        text NOT NULL,
  size_bytes          integer NOT NULL,
  sha256              text NOT NULL,
  original_name       text,
  source              text NOT NULL DEFAULT 'upload',                  -- upload | import
  -- For imported files: the Google Drive link the sheet held. Kept for traceability only; never served.
  legacy_url          text,
  uploaded_by         uuid REFERENCES public.users (id),
  uploaded_by_name    text NOT NULL,
  uploaded_at         timestamptz NOT NULL DEFAULT now(),
  attached_at         timestamptz,
  superseded_at       timestamptz,
  superseded_by       uuid REFERENCES public.tata_h_promise_files (id),
  CONSTRAINT tata_h_promise_files_size_positive CHECK (size_bytes > 0)
);

CREATE UNIQUE INDEX IF NOT EXISTS tata_h_promise_files_current_vehicle_kind
  ON public.tata_h_promise_files (vehicle_id, kind)
  WHERE attached_at IS NOT NULL AND superseded_at IS NULL AND booking_id IS NULL;
CREATE UNIQUE INDEX IF NOT EXISTS tata_h_promise_files_current_booking_kind
  ON public.tata_h_promise_files (booking_id, kind)
  WHERE attached_at IS NOT NULL AND superseded_at IS NULL AND booking_id IS NOT NULL;
-- Makes the import idempotent: the same Drive link is never copied twice for the same vehicle and slot.
CREATE UNIQUE INDEX IF NOT EXISTS tata_h_promise_files_import_key
  ON public.tata_h_promise_files (vehicle_id, kind, legacy_url) WHERE legacy_url IS NOT NULL;
CREATE INDEX IF NOT EXISTS tata_h_promise_files_vehicle_idx
  ON public.tata_h_promise_files (vehicle_id, kind, uploaded_at DESC);
CREATE INDEX IF NOT EXISTS tata_h_promise_files_staged_idx
  ON public.tata_h_promise_files (uploaded_by, uploaded_at) WHERE attached_at IS NULL;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- 4. Events — append-only
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tata_h_promise_events (
  id              uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- RESTRICT, not SET NULL: SET NULL is an UPDATE, which the append-only trigger refuses (see 0071). Vehicles
  -- are soft-deleted only, so this never blocks the app.
  vehicle_id      uuid REFERENCES public.tata_h_promise_vehicles (id) ON DELETE RESTRICT,
  subject         text NOT NULL DEFAULT 'vehicle',       -- vehicle | booking | option | setting | exchange_bonus
  subject_id      uuid,
  stock_no        integer,
  reg_no          text,
  action          text NOT NULL,
  from_status     text,
  to_status       text,
  actor_id        uuid REFERENCES public.users (id),
  actor_name      text NOT NULL,
  actor_role      text,
  remarks         text,
  -- {field: {from, to}}. Personal fields are written as {changed: true} — never the values.
  changes         jsonb NOT NULL DEFAULT '{}'::jsonb,
  created_at      timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS tata_h_promise_events_vehicle_idx
  ON public.tata_h_promise_events (vehicle_id, created_at DESC);
CREATE INDEX IF NOT EXISTS tata_h_promise_events_subject_idx
  ON public.tata_h_promise_events (subject, subject_id, created_at DESC);

CREATE OR REPLACE FUNCTION public.tata_h_promise_events_append_only()
  RETURNS trigger
  LANGUAGE plpgsql
  SET search_path = ''
AS $$
BEGIN
  RAISE EXCEPTION 'tata_h_promise_events is append-only (% refused)', TG_OP;
END;
$$;

CREATE OR REPLACE TRIGGER tata_h_promise_events_append_only
  BEFORE UPDATE OR DELETE ON public.tata_h_promise_events
  FOR EACH ROW EXECUTE FUNCTION public.tata_h_promise_events_append_only();

CREATE OR REPLACE TRIGGER tata_h_promise_events_no_truncate
  BEFORE TRUNCATE ON public.tata_h_promise_events
  FOR EACH STATEMENT EXECUTE FUNCTION public.tata_h_promise_events_append_only();

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- 5. Editable name lists
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tata_h_promise_options (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  kind              text NOT NULL,                        -- staff | approver | location
  -- The stable value stored on vehicle rows. Renaming changes only the label.
  value             text NOT NULL,
  label             text NOT NULL,
  sort_order        integer NOT NULL DEFAULT 0,
  -- Deactivating hides an option from the forms but keeps it valid on the rows that already use it.
  is_active         boolean NOT NULL DEFAULT true,
  created_by        uuid REFERENCES public.users (id),
  created_by_name   text,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_by        uuid REFERENCES public.users (id),
  updated_by_name   text,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tata_h_promise_options_kind_value_key UNIQUE (kind, value),
  CONSTRAINT tata_h_promise_options_value_nonblank CHECK (length(btrim(value)) > 0),
  CONSTRAINT tata_h_promise_options_label_nonblank CHECK (length(btrim(label)) > 0)
);

-- Seeded from the Apps Script's fixed lists, plus the two values the sheet itself used that those lists lacked
-- (TATA RIASI, and Amandeep Singh Bain as a WhatsApp approver). Staff names are added by the one-time import.
INSERT INTO public.tata_h_promise_options (kind, value, label, sort_order, created_by_name)
VALUES
  ('location', 'TATA NARWAL',   'Narwal',          10, 'Migration 0072'),
  ('location', 'TATA LAMBERI',  'Lamberi',         20, 'Migration 0072'),
  ('location', 'TATA POONCH',   'Poonch',          30, 'Migration 0072'),
  ('location', 'TATA KATHUA',   'Kathua',          40, 'Migration 0072'),
  ('location', 'TATA SUPWAL',   'Supwal',          50, 'Migration 0072'),
  ('location', 'TATA RIASI',    'Riasi',           60, 'Migration 0072'),
  ('approver', 'SANJAY MAHAJAN', 'Sanjay Mahajan', 10, 'Migration 0072'),
  ('approver', 'ANKUR MAHAJAN',  'Ankur Mahajan',  20, 'Migration 0072'),
  ('approver', 'ARYAN MAHAJAN',  'Aryan Mahajan',  30, 'Migration 0072'),
  ('approver', 'TARUN MALHOTRA', 'Tarun Malhotra', 40, 'Migration 0072'),
  ('approver', 'AMANDEEP SINGH BAIN', 'Amandeep Singh Bain', 50, 'Migration 0072')
ON CONFLICT (kind, value) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- 6. Effective-dated settings (interest rate etc.)
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- A new rate is a new row with its own effective_from, so a rate change never rewrites last year's profit.
-- lib/h-promise/economics.ts applies each rate to the days it was in force.
CREATE TABLE IF NOT EXISTS public.tata_h_promise_settings (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  key               text NOT NULL,
  effective_from    date NOT NULL,
  value             jsonb NOT NULL,
  note              text,
  created_by        uuid REFERENCES public.users (id),
  created_by_name   text NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT tata_h_promise_settings_key_from_key UNIQUE (key, effective_from)
);

-- The sheet's interest formula: ROUND(days × 0.0003287671233 × purchase price) — 12 % a year ÷ 365, confirmed
-- against every row of the owner's workbook (scripts/fixtures/h-promise-economics.json).
INSERT INTO public.tata_h_promise_settings (key, effective_from, value, note, created_by_name)
VALUES ('interest_rate_annual_pct', DATE '2000-01-01', '{"ratePct": 12}'::jsonb,
        'From the Google Sheet: 0.0003287671233 a day = 12 % a year on the purchase price (without GST).',
        'Migration 0072')
ON CONFLICT (key, effective_from) DO NOTHING;

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- 7. Exchange bonus register
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS public.tata_h_promise_exchange_bonuses (
  id                uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  -- Nullable: the sheet tab never recorded a date, and inventing one for imported rows would look measured.
  entry_date        date,
  vehicle_no        text NOT NULL,
  vehicle_no_key    text GENERATED ALWAYS AS (upper(regexp_replace(vehicle_no, '[^A-Za-z0-9]', '', 'g'))) STORED,
  vehicle_name      text,
  sales_consultant  text,
  new_car_model     text NOT NULL,
  bonus_amount      numeric(12,2) NOT NULL,
  customer_phone    text,
  remarks           text,
  created_by        uuid REFERENCES public.users (id),
  created_by_name   text NOT NULL,
  created_at        timestamptz NOT NULL DEFAULT now(),
  updated_by        uuid REFERENCES public.users (id),
  updated_by_name   text,
  updated_at        timestamptz NOT NULL DEFAULT now(),
  deleted_at        timestamptz,
  deleted_by        uuid REFERENCES public.users (id),
  deleted_by_name   text,
  import_batch      text,
  import_row        integer,
  CONSTRAINT tata_h_promise_exchange_bonuses_amount_nonneg CHECK (bonus_amount >= 0)
);

CREATE INDEX IF NOT EXISTS tata_h_promise_exchange_bonuses_date_idx
  ON public.tata_h_promise_exchange_bonuses (entry_date DESC NULLS LAST, created_at DESC) WHERE deleted_at IS NULL;
CREATE INDEX IF NOT EXISTS tata_h_promise_exchange_bonuses_vehicle_idx
  ON public.tata_h_promise_exchange_bonuses (vehicle_no_key);

-- ─────────────────────────────────────────────────────────────────────────────────────────────────
-- RLS lockdown (as 0071). The app connects as `postgres` (owner, BYPASSRLS) and is unaffected. The public anon
-- key and signed-in browser tabs get nothing: these rows carry buyers' and sellers' identity documents.
-- ─────────────────────────────────────────────────────────────────────────────────────────────────
ALTER TABLE public.tata_h_promise_vehicles         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tata_h_promise_bookings         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tata_h_promise_files            ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tata_h_promise_events           ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tata_h_promise_options          ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tata_h_promise_settings         ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tata_h_promise_exchange_bonuses ENABLE ROW LEVEL SECURITY;

REVOKE ALL ON public.tata_h_promise_vehicles         FROM anon, authenticated, PUBLIC;
REVOKE ALL ON public.tata_h_promise_bookings         FROM anon, authenticated, PUBLIC;
REVOKE ALL ON public.tata_h_promise_files            FROM anon, authenticated, PUBLIC;
REVOKE ALL ON public.tata_h_promise_events           FROM anon, authenticated, PUBLIC;
REVOKE ALL ON public.tata_h_promise_options          FROM anon, authenticated, PUBLIC;
REVOKE ALL ON public.tata_h_promise_settings         FROM anon, authenticated, PUBLIC;
REVOKE ALL ON public.tata_h_promise_exchange_bonuses FROM anon, authenticated, PUBLIC;
REVOKE ALL ON SEQUENCE public.tata_h_promise_vehicles_stock_no_seq FROM anon, authenticated, PUBLIC;

GRANT ALL ON public.tata_h_promise_vehicles         TO service_role;
GRANT ALL ON public.tata_h_promise_bookings         TO service_role;
GRANT ALL ON public.tata_h_promise_files            TO service_role;
GRANT ALL ON public.tata_h_promise_events           TO service_role;
GRANT ALL ON public.tata_h_promise_options          TO service_role;
GRANT ALL ON public.tata_h_promise_settings         TO service_role;
GRANT ALL ON public.tata_h_promise_exchange_bonuses TO service_role;
GRANT ALL ON SEQUENCE public.tata_h_promise_vehicles_stock_no_seq TO service_role;

REVOKE ALL ON FUNCTION public.tata_h_promise_price_lock()          FROM anon, authenticated, PUBLIC;
REVOKE ALL ON FUNCTION public.tata_h_promise_events_append_only()  FROM anon, authenticated, PUBLIC;

COMMIT;

-- Verification (scripts/apply-migration-0072.ts runs all of these):
-- SELECT relname, relrowsecurity FROM pg_class WHERE relname LIKE 'tata_h_promise_%' AND relkind = 'r';  -- 7 rows, all true
-- SELECT table_name, grantee FROM information_schema.role_table_grants
--  WHERE table_name LIKE 'tata_h_promise_%' AND grantee IN ('anon','authenticated','PUBLIC');             -- ZERO rows
-- SELECT kind, count(*) FROM public.tata_h_promise_options GROUP BY kind;                                   -- location 6, approver 5
